### ISSUE TITLE
RPython does not call the anaconda3 python installation

### ISSUE THREAD

**Issue by poldap** [SimpleITK/ISBI2018_TUTORIAL#8]
Hi, 

Maybe you can help me out?
The notebook for the python installation worked perfectly, no complaints. After completing the whole compilation of code specified in the R part, however, I get this response at the R notebook:
![screenshot from 2018-04-02 17-22-18](https://user-images.githubusercontent.com/7040555/38202077-c20f22ec-369a-11e8-9a8e-af0726f57860.png)
![screenshot from 2018-04-02 17-22-58](https://user-images.githubusercontent.com/7040555/38202086-c963a69e-369a-11e8-9112-c86b21b93348.png)

I think the problem is that RPython is calling the wrong version of python, and in particular, not the one in the virtual environment. I have no clue why, and I have no clue how to fix it, since I have not used RPython before. 

Thank you kindly. BR,
/Pol

**Comment by zivy** [comment]
Based on the error message, I'd agree with your observation, wrong version of Python being called.
1. Did you activate the sitkISBI18 Anaconda environment before running the R notebook or are you in the base environment? This should change your path so that the correct python is invoked: `conda activate sitkISBI18`
2. If this doesn't work then it is hard to guess what is going on with the paths (obviously you have multiple Python versions installed). 
3. This isn't really a show stopper as the fetch_data is the only function that uses the rPython package.
4. Workaround:
    a. You already downloaded all of the data with the Python notebook (see data directory under python dir).
   b. Copy everything from python/data to r/data .
   c. Replace all the code in downloaddata.R with:
       ` fetch_data <- function(file_name)
{
  return(file.path("data", file_name))
}`

Run through the R notebook 02_images_and_resampling, if the third code cell (ReadImage) works then you are set.

Let us know if you encounter additional problems and we'll try our best to resolve them before the tutorial, otherwise we will resolve it at the beginning of the tutorial.

**Comment by poldap** [comment]
Hi,
Yes, I have several python installations xD. But yes, I was running the notebook from inside sitkISBI18 and the paths do not seem to change.
I've taken your way out (using the already downloaded data), however, and the 02_images_and_resampling run all the way through with no trouble at all, opening the images and all.
Thanks.
BR,
/Pol
